// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Track data: the Nordschleife centre line generated by tools/build_data.py
// (port of Open Street Kart's MapDataLoader / RacePath).

export interface Sector {
  name: string;
  s: number;
}

export interface TrackJSON {
  name: string;
  source: string;
  length: number;
  step: number;
  x: number[];
  z: number[];
  y: number[];
  bank: number[];
  half: number[];
  verge: number;
  /** verge cross-fall beyond the asphalt edge: [slope, extra slope after 1.2 m] (default Nordschleife ditches) */
  vergeFall?: [number, number];
  line: number[];
  lineCurv: number[];
  sectors: Sector[];
  crests: Sector[];
  terrain: { x0: number; z0: number; nx: number; nz: number; cell: number; hMin: number; scale: number };
  landcover: { x0: number; z0: number; nx: number; nz: number; cell: number };
  elevation: { min: number; max: number };
}

export interface TrackQuery {
  /** segment start sample */
  i: number;
  /** 0..1 along segment */
  t: number;
  /** distance along the lap, 0..length */
  s: number;
  /** signed lateral offset from the centre line, + = right of travel */
  lat: number;
  half: number;
  yc: number;
  bank: number;
}

const BUCKET = 40;

export class Track {
  readonly N: number;
  readonly step: number;
  readonly length: number;
  readonly x: Float32Array;
  readonly y: Float32Array;
  readonly z: Float32Array;
  readonly bank: Float32Array;
  readonly half: Float32Array;
  readonly line: Float32Array;
  readonly lineCurv: Float32Array;
  readonly tx: Float32Array;
  readonly tz: Float32Array;
  readonly curv: Float32Array;
  readonly verge: number;
  readonly vergeFall: [number, number];
  readonly sectors: Sector[];
  readonly crests: Sector[];
  readonly data: TrackJSON;
  private buckets = new Map<number, number[]>();

  constructor(d: TrackJSON) {
    this.data = d;
    this.N = d.x.length;
    this.step = d.step;
    this.length = d.length;
    this.x = Float32Array.from(d.x);
    this.y = Float32Array.from(d.y);
    this.z = Float32Array.from(d.z);
    this.bank = Float32Array.from(d.bank);
    this.half = Float32Array.from(d.half);
    this.line = Float32Array.from(d.line);
    this.lineCurv = Float32Array.from(d.lineCurv);
    this.verge = d.verge;
    this.vergeFall = d.vergeFall ?? [0.06, 0.05];
    this.sectors = d.sectors;
    this.crests = d.crests;
    const N = this.N;
    this.tx = new Float32Array(N);
    this.tz = new Float32Array(N);
    this.curv = new Float32Array(N);
    for (let i = 0; i < N; i++) {
      const a = (i - 1 + N) % N;
      const b = (i + 1) % N;
      const dx = this.x[b] - this.x[a];
      const dz = this.z[b] - this.z[a];
      const l = Math.hypot(dx, dz) || 1;
      this.tx[i] = dx / l;
      this.tz[i] = dz / l;
    }
    for (let i = 0; i < N; i++) {
      const a = (i - 1 + N) % N;
      const b = (i + 1) % N;
      const ha = Math.atan2(this.tx[a], -this.tz[a]);
      const hb = Math.atan2(this.tx[b], -this.tz[b]);
      let dh = hb - ha;
      while (dh > Math.PI) dh -= 2 * Math.PI;
      while (dh < -Math.PI) dh += 2 * Math.PI;
      this.curv[i] = dh / (2 * this.step);
    }
    for (let i = 0; i < N; i++) {
      const k = this.key(this.x[i], this.z[i]);
      let b = this.buckets.get(k);
      if (!b) this.buckets.set(k, (b = []));
      b.push(i);
    }
  }

  private key(x: number, z: number): number {
    return Math.floor(x / BUCKET) * 100003 + Math.floor(z / BUCKET);
  }

  wrap(i: number): number {
    return ((i % this.N) + this.N) % this.N;
  }

  wrapS(s: number): number {
    return ((s % this.length) + this.length) % this.length;
  }

  /** right-hand horizontal normal at sample i */
  rx(i: number): number {
    return -this.tz[i];
  }
  rz(i: number): number {
    return this.tx[i];
  }

  /** Signed distance a -> b along the loop in (-L/2, L/2]. */
  deltaS(a: number, b: number): number {
    let d = b - a;
    const L = this.length;
    d = ((d % L) + L) % L;
    if (d > L / 2) d -= L;
    return d;
  }

  private nearestGlobal(x: number, z: number): number {
    let best = -1;
    let bd = Infinity;
    const cx = Math.floor(x / BUCKET);
    const cz = Math.floor(z / BUCKET);
    for (let r = 1; r < 60 && best < 0; r++) {
      for (let ix = cx - r; ix <= cx + r; ix++) {
        for (let iz = cz - r; iz <= cz + r; iz++) {
          const b = this.buckets.get(ix * 100003 + iz);
          if (!b) continue;
          for (const i of b) {
            const d = (this.x[i] - x) ** 2 + (this.z[i] - z) ** 2;
            if (d < bd) {
              bd = d;
              best = i;
            }
          }
        }
      }
    }
    return Math.max(best, 0);
  }

  /** Project a world position on the centre line. `hint` = previous sample index (-1 for none). */
  query(x: number, z: number, hint = -1, out?: TrackQuery): TrackQuery {
    let best: number;
    if (hint < 0) {
      best = this.nearestGlobal(x, z);
    } else {
      best = hint;
      let bd = (this.x[hint] - x) ** 2 + (this.z[hint] - z) ** 2;
      // walk forward / backward while it improves (centre line is smooth & sampled every 2 m)
      for (const dir of [1, -1]) {
        let i = hint;
        for (let k = 0; k < 400; k++) {
          const j = this.wrap(i + dir);
          const d = (this.x[j] - x) ** 2 + (this.z[j] - z) ** 2;
          if (d < bd) {
            bd = d;
            best = j;
            i = j;
          } else break;
        }
      }
      if (bd > 60 * 60) best = this.nearestGlobal(x, z);
    }
    // choose segment (best-1,best) or (best,best+1) and project
    let i = best;
    const nx = this.wrap(best + 1);
    const px = this.wrap(best - 1);
    const fwd = (x - this.x[best]) * (this.x[nx] - this.x[best]) + (z - this.z[best]) * (this.z[nx] - this.z[best]);
    if (fwd < 0) i = px;
    const j = this.wrap(i + 1);
    const sx = this.x[j] - this.x[i];
    const sz = this.z[j] - this.z[i];
    const sl2 = sx * sx + sz * sz || 1;
    let t = ((x - this.x[i]) * sx + (z - this.z[i]) * sz) / sl2;
    t = Math.min(1, Math.max(0, t));
    const cx = this.x[i] + sx * t;
    const cz = this.z[i] + sz * t;
    const rx = -(this.tz[i] * (1 - t) + this.tz[j] * t);
    const rz = this.tx[i] * (1 - t) + this.tx[j] * t;
    const lat = (x - cx) * rx + (z - cz) * rz;
    const q = out ?? ({} as TrackQuery);
    q.i = i;
    q.t = t;
    q.s = (i + t) * this.step;
    q.lat = lat;
    q.half = this.half[i] * (1 - t) + this.half[j] * t;
    q.yc = this.y[i] * (1 - t) + this.y[j] * t;
    q.bank = this.bank[i] * (1 - t) + this.bank[j] * t;
    return q;
  }

  /** Rail distance from the centre line (asphalt half width + verge). */
  railDist(half: number): number {
    return half + this.verge;
  }

  /** Height of the drivable surface at lateral offset `lat`. */
  surfaceY(q: TrackQuery, lat = q.lat): number {
    const h = q.half;
    const tb = Math.tan(q.bank);
    const c = Math.max(-h, Math.min(h, lat));
    let y = q.yc + c * tb;
    const over = Math.abs(lat) - h;
    if (over > 0) y -= over * this.vergeFall[0] + Math.max(0, over - 1.2) * this.vergeFall[1]; // verge falls away slightly
    return y;
  }

  /** Interpolated centre line frame at distance s. */
  frameAt(s: number, out: { x: number; y: number; z: number; tx: number; tz: number; i: number; half: number; bank: number }) {
    const f = this.wrapS(s) / this.step;
    const i = Math.floor(f) % this.N;
    const j = (i + 1) % this.N;
    const t = f - Math.floor(f);
    out.x = this.x[i] + (this.x[j] - this.x[i]) * t;
    out.y = this.y[i] + (this.y[j] - this.y[i]) * t;
    out.z = this.z[i] + (this.z[j] - this.z[i]) * t;
    const tx = this.tx[i] + (this.tx[j] - this.tx[i]) * t;
    const tz = this.tz[i] + (this.tz[j] - this.tz[i]) * t;
    const l = Math.hypot(tx, tz) || 1;
    out.tx = tx / l;
    out.tz = tz / l;
    out.i = i;
    out.half = this.half[i] + (this.half[j] - this.half[i]) * t;
    out.bank = this.bank[i] + (this.bank[j] - this.bank[i]) * t;
    return out;
  }

  sectorAt(s: number): Sector {
    const ss = this.wrapS(s);
    let cur = this.sectors[0];
    for (const sec of this.sectors) {
      if (sec.s <= ss) cur = sec;
      else break;
    }
    return cur;
  }

  sectorIndex(name: string): number {
    return this.sectors.findIndex((s) => s.name === name);
  }
}

/** Terrain heightmap (Uint16 cm above hMin). */
export class Heightmap {
  readonly x0: number;
  readonly z0: number;
  readonly nx: number;
  readonly nz: number;
  readonly cell: number;
  readonly h: Float32Array;

  constructor(meta: TrackJSON["terrain"], raw: ArrayBuffer) {
    this.x0 = meta.x0;
    this.z0 = meta.z0;
    this.nx = meta.nx;
    this.nz = meta.nz;
    this.cell = meta.cell;
    const u = new Uint16Array(raw);
    this.h = new Float32Array(u.length);
    for (let i = 0; i < u.length; i++) this.h[i] = meta.hMin + u[i] * meta.scale;
  }

  get width() {
    return (this.nx - 1) * this.cell;
  }
  get depth() {
    return (this.nz - 1) * this.cell;
  }

  at(ix: number, iz: number): number {
    ix = Math.max(0, Math.min(this.nx - 1, ix));
    iz = Math.max(0, Math.min(this.nz - 1, iz));
    return this.h[iz * this.nx + ix];
  }

  height(x: number, z: number): number {
    const fx = (x - this.x0) / this.cell;
    const fz = (z - this.z0) / this.cell;
    const ix = Math.floor(fx);
    const iz = Math.floor(fz);
    const tx = fx - ix;
    const tz = fz - iz;
    const a = this.at(ix, iz);
    const b = this.at(ix + 1, iz);
    const c = this.at(ix, iz + 1);
    const d = this.at(ix + 1, iz + 1);
    // match the triangulation of the rendered grid (diagonal from (0,0) to (1,1))
    if (tx > tz) return a + (b - a) * tx + (d - b) * tz;
    return a + (d - c) * tx + (c - a) * tz;
  }
}
